# Generated by Django 6.0.6 on 2026-06-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=50)),
                ('jam', models.TimeField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.admin')),
            ],
        ),
        migrations.CreateModel(
            name='KelolaStatusAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.admin')),
            ],
        ),
        migrations.CreateModel(
            name='LihatRekapAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.guru')),
            ],
        ),
        migrations.CreateModel(
            name='LihatRiwayatKehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('id_ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.orangtua')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_qr', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.admin')),
            ],
        ),
        migrations.CreateModel(
            name='MelakukanAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadir.siswa')),
            ],
        ),
    ]
